// Stamps the build's identity into src/version.ts (git-ignored, regenerated each
// build). Runs as the agent's `prebuild`/`predev` hook. The agent is always built
// right after the installer syncs git, so the commit here is exactly what's
// deployed. Falls back to the package.json version alone when git is unavailable.
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const agentDir = new URL('..', import.meta.url);
const pkg = JSON.parse(readFileSync(new URL('package.json', agentDir), 'utf8'));
const version = pkg.version ?? '0.0.0';

function git(args) {
  try {
    return execSync(`git ${args}`, {
      cwd: new URL('.', agentDir),
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
  } catch {
    return '';
  }
}

const commit = git('rev-parse --short HEAD');
const dirty = commit && git('status --porcelain') ? '-dirty' : '';
const date = git('show -s --format=%cs HEAD'); // commit date, YYYY-MM-DD
const full = commit ? `${version}+${commit}${dirty}` : version;

const body = `// AUTO-GENERATED by scripts/stamp-version.mjs — do not edit or commit.
export const AGENT_VERSION = ${JSON.stringify(full)};
export const AGENT_BUILD = ${JSON.stringify({ version, commit: commit || null, date: date || null })};
`;
writeFileSync(new URL('src/version.ts', agentDir), body);
console.log(`[stamp] AGENT_VERSION=${full}`);
